### ISSUE TITLE
##[error]Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by Prateek13727** [sarthak-saxena/JSBundleSize#6]
Hey
I get the following error when JSBundleSize action is executed
![image](https://user-images.githubusercontent.com/18599528/79849727-7eb62280-83e0-11ea-8a05-af93a7c16db9.png)

my .yml file

```

name: github-flow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  compute-bundle-size:
    name: Compute JS Bundle size
    runs-on: ubuntu-latest
      - uses: actions/checkout@master
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: yarn install --ignore-engines
          build_command: yarn build:prod
          dist: 'dist' 
          token: ${{ secrets.GITHUB_TOKEN }} 
```

my GitHub repo [here](https://github.com/Prateek13727/hashtag-magic).

Please let me know in the comments in case any more clarification is needed!

Cheers
Prateek

**Comment by sarthak-saxena** [comment]
Looks like the config is wrong here, please try with 
```
- uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: 'yarn install --ignore-engines'
          build_command: 'yarn build:prod'
          dist: 'dist' 
          token: ${{ secrets.GITHUB_TOKEN }} 
```
basically config parameters bootstrap & build_command expects `string` data type
